/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The dfu_peer_sig marshal type declarations. This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools/packages/typegen/typegen.py.
*/

#ifndef _DFU_PEER_SIG_MARSHAL_TYPEDEF_H__
#define _DFU_PEER_SIG_MARSHAL_TYPEDEF_H__

#include <csrtypes.h>
#include <app/marshal/marshal_if.h>


#define DFU_PEER_SIG_MARSHAL_TYPES_TABLE(ENTRY)\
    ENTRY(dfu_peer_erase_req_res_t)\
    ENTRY(dfu_peer_device_not_in_use_t)

#define EXPAND_AS_ENUMERATION(type) MARSHAL_TYPE(type),
enum DFU_PEER_SIG_MARSHAL_TYPES
{
    DFU_PEER_SIG_MARSHAL_TYPES_TABLE(EXPAND_AS_ENUMERATION)
    NUMBER_OF_DFU_PEER_SIG_MARSHAL_TYPES
} ;

#undef EXPAND_AS_ENUMERATION

extern const marshal_type_descriptor_t * const dfu_peer_sig_marshal_type_descriptors[];
#endif /* _DFU_PEER_SIG_MARSHAL_TYPEDEF_H__ */

