/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_output_volume.h
    \brief The chain_output_volume chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_OUTPUT_VOLUME_H__
#define _CHAIN_OUTPUT_VOLUME_H__

/*!
\page chain_output_volume
@startuml
    object OPR_SOURCE_SYNC
    OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
    object OPR_VOLUME_CONTROL
    OPR_VOLUME_CONTROL : id = HS_CAP_ID_VOL_CTRL_VOL
    OPR_VOLUME_CONTROL "MAIN_IN_L(0)"<-- "OUT_L(0)" OPR_SOURCE_SYNC
    OPR_VOLUME_CONTROL "MAIN_IN_R(2)"<-- "OUT_R(1)" OPR_SOURCE_SYNC
    object EPR_SINK_STEREO_MIXER_L #lightgreen
    OPR_SOURCE_SYNC "IN_L(0)" <-- EPR_SINK_STEREO_MIXER_L
    object EPR_SINK_STEREO_MIXER_R #lightgreen
    OPR_SOURCE_SYNC "IN_R(1)" <-- EPR_SINK_STEREO_MIXER_R
    object EPR_VOLUME_AUX #lightgreen
    OPR_VOLUME_CONTROL "AUX_IN(1)" <-- EPR_VOLUME_AUX
    object EPR_SOURCE_STEREO_OUTPUT_L #lightblue
    EPR_SOURCE_STEREO_OUTPUT_L <-- "OUT_L(0)" OPR_VOLUME_CONTROL
    object EPR_SOURCE_STEREO_OUTPUT_R #lightblue
    EPR_SOURCE_STEREO_OUTPUT_R <-- "OUT_R(1)" OPR_VOLUME_CONTROL
@enduml
*/

#include <chain.h>

extern const chain_config_t chain_output_volume_config;

#endif /* _CHAIN_OUTPUT_VOLUME_H__ */

