/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_output_volume_no_passthrough.h
    \brief The chain_output_volume_no_passthrough chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_OUTPUT_VOLUME_NO_PASSTHROUGH_H__
#define _CHAIN_OUTPUT_VOLUME_NO_PASSTHROUGH_H__

/*!
\page chain_output_volume_no_passthrough
@startuml
    object OPR_SOURCE_SYNC
    OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
    object OPR_VOLUME_CONTROL
    OPR_VOLUME_CONTROL : id = HS_CAP_ID_VOL_CTRL_VOL
    OPR_VOLUME_CONTROL "MAIN_IN(0)"<-- "OUT(0)" OPR_SOURCE_SYNC
    object EPR_SINK_MIXER_MAIN_IN #lightgreen
    OPR_SOURCE_SYNC "IN(0)" <-- EPR_SINK_MIXER_MAIN_IN
    object EPR_VOLUME_AUX #lightgreen
    OPR_VOLUME_CONTROL "AUX_IN(1)" <-- EPR_VOLUME_AUX
    object EPR_SOURCE_STEREO_OUTPUT_L #lightblue
    EPR_SOURCE_STEREO_OUTPUT_L <-- "OUT(0)" OPR_VOLUME_CONTROL
@enduml
*/

#include <chain.h>

extern const chain_config_t chain_output_volume_no_passthrough_config;

#endif /* _CHAIN_OUTPUT_VOLUME_NO_PASSTHROUGH_H__ */

