/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_input_aptxhd_stereo.h
    \brief The chain_input_aptxhd_stereo chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_INPUT_APTXHD_STEREO_H__
#define _CHAIN_INPUT_APTXHD_STEREO_H__

/*!
\page chain_input_aptxhd_stereo
@startuml
    object OPR_RTP_DECODER
    OPR_RTP_DECODER : id = CAP_ID_RTP_DECODE
    object OPR_APTXHD_DECODER
    OPR_APTXHD_DECODER : id = CAP_ID_APTXHD_DECODER
    OPR_APTXHD_DECODER "IN(0)"<-- "OUT(0)" OPR_RTP_DECODER
    object EPR_SINK_MEDIA #lightgreen
    OPR_RTP_DECODER "IN(0)" <-- EPR_SINK_MEDIA
    object EPR_SOURCE_DECODED_PCM #lightblue
    EPR_SOURCE_DECODED_PCM <-- "OUT_0(0)" OPR_APTXHD_DECODER
    object EPR_SOURCE_DECODED_PCM_RIGHT #lightblue
    EPR_SOURCE_DECODED_PCM_RIGHT <-- "OUT_1(1)" OPR_APTXHD_DECODER
@enduml
*/

#include <chain.h>

extern const chain_config_t chain_input_aptxhd_stereo_config_p0;

extern const chain_config_t chain_input_aptxhd_stereo_config_p1;

#endif /* _CHAIN_INPUT_APTXHD_STEREO_H__ */

