/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_tone_gen_no_iir.h
    \brief The chain_tone_gen_no_iir chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_TONE_GEN_NO_IIR_H__
#define _CHAIN_TONE_GEN_NO_IIR_H__

/*!
\page chain_tone_gen_no_iir
@startuml
    object OPR_TONE_GEN
    OPR_TONE_GEN : id = CAP_ID_RINGTONE_GENERATOR
    object OPR_TONE_PROMPT_BUFFER
    OPR_TONE_PROMPT_BUFFER : id = CAP_ID_BASIC_PASS
    OPR_TONE_PROMPT_BUFFER "IN(0)"<-- "OUT(0)" OPR_TONE_GEN
    object EPR_TONE_PROMPT_CHAIN_OUT #lightblue
    EPR_TONE_PROMPT_CHAIN_OUT <-- "OUT(0)" OPR_TONE_PROMPT_BUFFER
@enduml
*/

#include <chain.h>

extern const chain_config_t chain_tone_gen_no_iir_config;

#endif /* _CHAIN_TONE_GEN_NO_IIR_H__ */

