/*
    Warning - this file was autogenerated by genparse
    DO NOT EDIT - any changes will be lost
*/

#include "device_test_parse.h"

#include <ctype.h>
#include <panic.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <util.h> /* hash and compare */

#if defined(__KALIMBA__) && !defined(__GNUC__)
/* suppress warning caused for 'res' as compiler does not track into calls */
#pragma unitsuppress PossiblyUninitialized

/* Prototype of UtilHash differs on some versions of Kalimba libraries */
#define UTIL_HASH(_data,_size,_seed) UtilHash((const uint8*)(_data),_size,_seed)
#else
#define UTIL_HASH(_data,_size,_seed) UtilHash((const uint16*)(_data),_size,_seed)
#endif

typedef const uint8 *ptr;

static __inline__ char my_toupper(char c)
{ return (char)('a' <= c && c <= 'z' ? c +'A'-'a' : c); }

static const int hexdigit[] =
{
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,
    0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};

static ptr skip1(ptr s, ptr e)
{
  if(s)
    while(s != e && (*s == ' ' || *s == '\t'))
      ++s;
  return s;
}

static ptr match1(ptr s, ptr e)
{ return s && s != e && (*s == '\r' || *s == '\n') ? s+1 : 0; }

#ifdef TEST_HARNESS
static void printString(const char *name, const struct sequence *s)
{
  uint16 i;
  printf(" %s='", name);
  for(i = 0; i < s->length; ++i) putchar(s->data[i]);
  printf("'");
}
#endif

static __inline__ int isClass(char c, const int *a)
{
    return (c & ~0x7F) == 0 && a[(int)c];
}
 
static __inline__ ptr skipQuote(ptr p, ptr e)
{ return p && p != e && *p == '"' ? p+1 : p; }

static ptr getClassPlus(ptr p, ptr e, struct sequence *res, const int *a)
{
  p = skipQuote(p, e);
  if(p)
  {
    ptr s = p;
    while(p != e && isClass(*p, a)) ++p;
    if(p != s)
    {
        res->data = s;
        res->length = (uint16)(p - s);
			return skipQuote(p, e);
    }
    else
    {
        p = skipQuote(p, e);
        if (*p==',' || *p == '\r')
        {
            res->data = 0;
            res->length = 0;
            return 0;
        }
    }
  }
  res->data = 0;
  res->length = 0;
  return 0;
}

static ptr skipOnce1(ptr s, ptr e)
{
  if(s)
  {
    if(s != e && (*s == ',' || *s == ';'))
      ++s;
  }
  return s;
}

static ptr getWildString(ptr p, ptr e, struct sequence *res)
{
  if(p)
  {
    ptr s = p;
    p = (uint8*)UtilFind(0xFFFF, '\r', (const uint16*)p, 0, 1, (uint16) (e - p));
    if (!p) p = (uint8*)UtilFind(0xFFFF, '\n', (const uint16*)p, 0, 1, (uint16) (e - p));
    if (!p) p = e;
    res->data = s;
    res->length = (uint16)(p - s);
    return p;
  }
  res->data = 0;
  res->length = 0;
  return 0;
}

static ptr matchChar(ptr s, ptr e, uint8 c)
{ return s && s != e && my_toupper((char) *s) == (char) c ? s+1 : 0; }

static ptr findEndOfPacket(ptr s, ptr e)
{
  /*
     Returns
     0   if the buffer holds an incomplete packet
     s+1 if the buffer holds an invalid packet
     end of the first packet otherwise
  */
  if(s == e) return 0;

  if(*s == '\r')
  {
    /* expecting <cr> <lf> ... <cr> <lf> */
    if(e-s >= 4)
    {
      if(s[1] == '\n' && s[2] != '\r')
      {
        ptr p = s+2;
        if(*p != '\r')
        {
#ifndef TEST_HARNESS
        p = (const uint8*)UtilFind(0xFFFF, '\r', (const uint16*)p, 0, 1, (uint16)(e-p));
#endif
#ifdef TEST_HARNESS
		   while(p != e && *p != '\r') p++;
#endif
        return p == 0 || p + 1 == e ? 0 /* no terminator yet */
             : p[1] == '\n' ? p+2 /* valid */
             : s+1 ; /* invalid terminator */
         }
         else
             return s+1;
      }
      else
      {
        return s+1;
      }
    }
    else
    {
      /* Can't tell yet */
      return 0;
    }
  }
  else
  {
    /* expecting ... <cr> */
    ptr p = s;
    while(p != e && (*p == ' ' || *p == '\0' || *p == '\t')) ++p;
    if(p != e && (*p == '\r' || *p == '\n' )) return s+1;
    while(p != e && *p != '\r') ++p;
    return p == e ? 0 : p+1;
  }
}

#ifndef TEST_HARNESS
#if (defined __XAP__ || defined __KALIMBA__)
uint16 DeviceTestServiceParser_parseSource(Source rfcDataIn, Task task)
{
  ptr s = SourceMap(rfcDataIn);
  ptr e = s + SourceSize(rfcDataIn);
  ptr p = DeviceTestServiceParser_parseData(s, e, task);
  if(p != s)
  {
    SourceDrop(rfcDataIn, (uint16) (p - s));
    return 1;
  }
  else
  {
    return 0;
  }
}
#endif
#endif

typedef struct {
  char c;
  int16 to;
} Arc;

static const Arc arcs[] = {
  { '\t', 0 },
  { ' ', 0 },
  { 'A', 1 },
  { 'T', 2 },
  { '\t', 2 },
  { ' ', 2 },
  { '+', 3 },
  { '\t', 3 },
  { ' ', 3 },
  { 'A', 4 },
  { 'B', 5 },
  { 'D', 6 },
  { 'L', 7 },
  { 'P', 8 },
  { 'R', 9 },
  { 'T', 10 },
  { 'N', 11 },
  { 'U', 12 },
  { 'A', 13 },
  { 'T', 14 },
  { 'O', 15 },
  { 'S', 16 },
  { 'F', 17 },
  { 'S', 18 },
  { 'E', 19 },
  { 'C', 20 },
  { 'D', 21 },
  { 'T', 22 },
  { 'T', 23 },
  { 'S', 24 },
  { 'C', 25 },
  { 'O', 26 },
  { 'K', 27 },
  { 'T', 28 },
  { 'S', 29 },
  { 'M', 30 },
  { 'S', 31 },
  { 'D', 32 },
  { 'E', 33 },
  { 'G', 34 },
  { 'R', 35 },
  { 'S', 36 },
  { 'W', 37 },
  { 'I', 38 },
  { 'H', 39 },
  { 'T', 40 },
  { 'E', 41 },
  { 'S', 42 },
  { 'T', 43 },
  { 'A', 44 },
  { 'P', 45 },
  { 'E', 46 },
  { 'E', 47 },
  { 'I', 48 },
  { 'P', 49 },
  { 'T', 50 },
  { 'I', 51 },
  { 'N', 52 },
  { 'E', 53 },
  { 'E', 54 },
  { 'E', 55 },
  { 'R', 56 },
  { 'O', 57 },
  { 'D', 58 },
  { 'R', 59 },
  { 'S', 60 },
  { 'E', 61 },
  { 'N', 62 },
  { 'E', 63 },
  { 'E', 64 },
  { 'L', 65 },
  { 'B', 66 },
  { 'Y', 67 },
  { 'S', 68 },
  { 'R', 69 },
  { 'E', 70 },
  { 'A', 71 },
  { 'H', 72 },
  { 'L', 73 },
  { 'P', 74 },
  { 'T', 75 },
  { 'S', 76 },
  { 'A', 77 },
  { 'T', 78 },
  { 'A', 79 },
  { 'T', 80 },
  { 'I', 81 },
  { 'P', 82 },
  { 'I', 83 },
  { 'E', 84 },
  { 'T', 85 },
  { 'R', 86 },
  { 'D', 87 },
  { 'T', 88 },
  { 'S', 89 },
  { 'B', 90 },
  { 'A', 91 },
  { 'C', 92 },
  { 'G', 93 },
  { 'M', 94 },
  { 'S', 95 },
  { 'T', 96 },
  { 'E', 97 },
  { 'R', 98 },
  { 'C', 99 },
  { 'A', 100 },
  { 'E', 101 },
  { 'I', 102 },
  { 'R', 103 },
  { 'O', 104 },
  { 'A', 105 },
  { 'B', 106 },
  { 'P', 107 },
  { 'D', 108 },
  { 'F', 109 },
  { 'P', 110 },
  { 'T', 111 },
  { 'L', 112 },
  { 'S', 113 },
  { 'S', 114 },
  { 'A', 115 },
  { 'Y', 116 },
  { 'T', 117 },
  { 'T', 118 },
  { 'T', 119 },
  { 'D', 120 },
  { 'C', 121 },
  { 'L', 122 },
  { 'E', 123 },
  { 'I', 124 },
  { 'E', 125 },
  { 'C', 126 },
  { 'D', 127 },
  { 'L', 128 },
  { 'S', 129 },
  { 'T', 130 },
  { 'A', 131 },
  { 'A', 132 },
  { 'C', 133 },
  { 'L', 134 },
  { 'D', 135 },
  { 'O', 136 },
  { 'O', 137 },
  { 'U', 138 },
  { 'B', 139 },
  { 'L', 140 },
  { 'S', 141 },
  { 'F', 142 },
  { 'I', 143 },
  { 'S', 144 },
  { 'E', 145 },
  { 'A', 146 },
  { 'A', 147 },
  { 'P', 148 },
  { 'R', 149 },
  { 'L', 150 },
  { 'E', 151 },
  { 'E', 152 },
  { 'M', 153 },
  { 'A', 154 },
  { 'K', 155 },
  { 'E', 156 },
  { 'T', 157 },
  { 'B', 158 },
  { 'T', 159 },
  { 'A', 160 },
  { 'F', 161 },
  { 'U', 162 },
  { 'E', 163 },
  { 'T', 164 },
  { 'X', 165 },
  { 'D', 166 },
  { 'T', 167 },
  { 'E', 168 },
  { 'L', 169 },
  { '\t', 135 },
  { ' ', 135 },
  { ':', -1 },
  { '=', -1 },
  { 'I', 170 },
  { 'O', 171 },
  { 'X', 172 },
  { 'C', 173 },
  { 'L', 174 },
  { 'E', 175 },
  { 'K', 176 },
  { 'I', 177 },
  { 'N', 178 },
  { 'K', 179 },
  { 'F', 180 },
  { 'Y', 181 },
  { 'B', 182 },
  { '\t', 148 },
  { ' ', 148 },
  { ':', -2 },
  { '=', -2 },
  { 'T', 183 },
  { 'E', 184 },
  { 'S', 185 },
  { 'S', 186 },
  { 'O', 187 },
  { 'D', 188 },
  { 'S', 189 },
  { 'A', 190 },
  { '\t', 157 },
  { ' ', 157 },
  { ':', -3 },
  { '=', -3 },
  { 'G', 191 },
  { '\t', 159 },
  { ' ', 159 },
  { ':', -4 },
  { '=', -4 },
  { 'R', 192 },
  { 'G', 193 },
  { 'T', 194 },
  { 'R', 195 },
  { 'T', 196 },
  { 'O', 197 },
  { 'S', 198 },
  { '\t', 166 },
  { '\n', -5 },
  { '\r', -5 },
  { ' ', 166 },
  { 'U', 199 },
  { 'L', 200 },
  { 'E', 201 },
  { 'N', 202 },
  { 'U', 203 },
  { 'I', 204 },
  { 'H', 205 },
  { 'E', 206 },
  { '\t', 175 },
  { ' ', 175 },
  { ':', -6 },
  { '=', -6 },
  { 'E', 207 },
  { 'N', 208 },
  { 'E', 209 },
  { 'E', 210 },
  { 'I', 211 },
  { 'T', 212 },
  { 'L', 213 },
  { '\t', 183 },
  { '\n', -7 },
  { '\r', -7 },
  { ' ', 183 },
  { 'V', 214 },
  { 'T', 215 },
  { 'T', 216 },
  { 'D', 217 },
  { 'D', 218 },
  { 'T', 219 },
  { 'R', 220 },
  { 'E', 221 },
  { 'R', 222 },
  { 'A', 223 },
  { 'C', 224 },
  { 'P', 225 },
  { 'S', 226 },
  { 'M', 227 },
  { 'X', 228 },
  { 'X', 229 },
  { 'P', 230 },
  { 'T', 231 },
  { 'R', 232 },
  { 'E', 233 },
  { 'F', 234 },
  { 'P', 235 },
  { 'T', 236 },
  { 'M', 237 },
  { '\t', 205 },
  { ' ', 205 },
  { ':', -8 },
  { '=', -8 },
  { '\t', 206 },
  { '\n', -9 },
  { '\r', -9 },
  { ' ', 206 },
  { 'Y', 238 },
  { 'E', 239 },
  { 'G', 240 },
  { 'Y', 241 },
  { 'N', 242 },
  { 'E', 243 },
  { 'O', 244 },
  { 'E', 245 },
  { 'E', 246 },
  { 'I', 247 },
  { 'M', 248 },
  { 'E', 249 },
  { 'R', 250 },
  { 'A', 251 },
  { 'O', 252 },
  { '\t', 220 },
  { ' ', 220 },
  { ':', -10 },
  { '=', -10 },
  { 'T', 253 },
  { 'I', 254 },
  { 'D', 255 },
  { 'H', 256 },
  { 'A', 257 },
  { 'O', 258 },
  { 'T', 259 },
  { 'O', 260 },
  { 'S', 261 },
  { 'S', 262 },
  { '\t', 230 },
  { '\n', -11 },
  { '\r', -11 },
  { ' ', 230 },
  { 'A', 263 },
  { 'E', 264 },
  { 'R', 265 },
  { 'F', 266 },
  { 'U', 267 },
  { 'P', 268 },
  { 'I', 269 },
  { '\t', 238 },
  { ' ', 238 },
  { ':', 270 },
  { '=', 270 },
  { 'G', 271 },
  { 'A', 272 },
  { '\t', 241 },
  { ' ', 241 },
  { ':', 273 },
  { '=', 273 },
  { 'E', 274 },
  { 'S', 275 },
  { 'N', 276 },
  { '\t', 245 },
  { '\n', -12 },
  { '\r', -12 },
  { ' ', 245 },
  { 'L', 277 },
  { 'N', 278 },
  { 'O', 279 },
  { '\t', 249 },
  { '\n', -13 },
  { '\r', -13 },
  { ' ', 249 },
  { '?', 280 },
  { '\t', 250 },
  { '\n', -14 },
  { '\r', -14 },
  { ' ', 250 },
  { '?', 281 },
  { 'R', 282 },
  { 'P', 283 },
  { '\t', 253 },
  { ' ', 253 },
  { ':', -15 },
  { '=', -15 },
  { 'E', 284 },
  { 'D', 285 },
  { 'A', 286 },
  { 'C', 287 },
  { 'W', 288 },
  { 'O', 289 },
  { 'D', 290 },
  { 'T', 291 },
  { 'T', 292 },
  { 'R', 293 },
  { '\t', 264 },
  { '\n', -16 },
  { '\r', -16 },
  { ' ', 264 },
  { '?', 294 },
  { 'O', 295 },
  { 'E', 296 },
  { 'T', 297 },
  { 'U', 298 },
  { 'T', 299 },
  { '\t', 270 },
  { ' ', 270 },
  { '0', 300 },
  { 'A', 301 },
  { 'I', 302 },
  { '\t', 273 },
  { ' ', 273 },
  { '0', 303 },
  { 'G', 304 },
  { 'T', 305 },
  { 'E', 306 },
  { '\t', 277 },
  { '\n', -17 },
  { '\r', -17 },
  { ' ', 277 },
  { '?', 307 },
  { 'G', 308 },
  { 'D', 309 },
  { '\t', 310 },
  { '\n', -13 },
  { '\r', -13 },
  { ' ', 310 },
  { '?', 280 },
  { '\t', 311 },
  { '\n', -14 },
  { '\r', -14 },
  { ' ', 311 },
  { '?', 281 },
  { 'T', 312 },
  { '\t', 283 },
  { '\n', -18 },
  { '\r', -18 },
  { ' ', 283 },
  { 'R', 313 },
  { 'R', 314 },
  { 'N', 315 },
  { 'K', 316 },
  { 'E', 317 },
  { 'P', 318 },
  { 'E', 319 },
  { 'A', 320 },
  { 'A', 321 },
  { 'T', 322 },
  { '\t', 323 },
  { '\n', -16 },
  { '\r', -16 },
  { ' ', 323 },
  { '?', 294 },
  { 'M', 324 },
  { 'C', 325 },
  { 'P', 326 },
  { 'S', 327 },
  { 'T', 328 },
  { 'Y', 329 },
  { 'X', -19 },
  { 'I', 330 },
  { 'N', 331 },
  { 'X', -20 },
  { 'A', 332 },
  { 'T', 333 },
  { '\t', 306 },
  { ' ', 306 },
  { ':', -21 },
  { '=', -21 },
  { '\t', 334 },
  { '\n', -17 },
  { '\r', -17 },
  { ' ', 334 },
  { '?', 307 },
  { '\t', 308 },
  { ' ', 308 },
  { ':', -22 },
  { '=', -22 },
  { 'E', 335 },
  { '\t', 310 },
  { '\n', -13 },
  { '\r', -13 },
  { ' ', 310 },
  { '\t', 311 },
  { '\n', -14 },
  { '\r', -14 },
  { ' ', 311 },
  { '\t', 312 },
  { ' ', 312 },
  { ':', -23 },
  { '=', -23 },
  { '\t', 313 },
  { ' ', 313 },
  { ':', -24 },
  { '=', -24 },
  { 'E', 336 },
  { 'N', 337 },
  { 'E', 338 },
  { 'R', 339 },
  { 'P', 340 },
  { 'T', 341 },
  { '\t', 319 },
  { '\n', -25 },
  { '\r', -25 },
  { ' ', 319 },
  { 'R', 342 },
  { 'R', 343 },
  { '\t', 322 },
  { '\n', -26 },
  { '\r', -26 },
  { ' ', 322 },
  { '\t', 323 },
  { '\n', -16 },
  { '\r', -16 },
  { ' ', 323 },
  { 'E', 344 },
  { 'T', 345 },
  { 'I', 346 },
  { '\t', 327 },
  { '\n', -27 },
  { '\r', -27 },
  { ' ', 327 },
  { '\t', 328 },
  { ' ', 328 },
  { ':', -28 },
  { '=', -28 },
  { '\t', 329 },
  { ' ', 329 },
  { ':', -29 },
  { '=', -29 },
  { 'N', 347 },
  { '\t', 348 },
  { ' ', 348 },
  { ':', -30 },
  { '=', -30 },
  { 'D', 349 },
  { 'I', 350 },
  { 'O', 351 },
  { '\t', 334 },
  { '\n', -17 },
  { '\r', -17 },
  { ' ', 334 },
  { '\t', 335 },
  { ' ', 335 },
  { ':', -31 },
  { '=', -31 },
  { 'S', 352 },
  { 'E', 353 },
  { 'T', 354 },
  { '\t', 339 },
  { ' ', 339 },
  { ':', -32 },
  { '=', -32 },
  { 'I', 355 },
  { 'I', 356 },
  { 'T', 357 },
  { 'T', 358 },
  { 'T', 359 },
  { '\t', 345 },
  { ' ', 345 },
  { ':', -33 },
  { '=', -33 },
  { 'O', 360 },
  { '\t', 361 },
  { ' ', 361 },
  { ':', -34 },
  { '=', -34 },
  { 'D', 362 },
  { '\t', 348 },
  { ' ', 348 },
  { ':', -30 },
  { '=', -30 },
  { 'U', 363 },
  { 'N', 364 },
  { 'N', 365 },
  { 'S', 366 },
  { 'L', 367 },
  { '\t', 354 },
  { ' ', 354 },
  { ':', 368 },
  { '=', 368 },
  { 'O', 369 },
  { 'M', 370 },
  { '\t', 357 },
  { ' ', 357 },
  { ':', -35 },
  { '=', -35 },
  { '\t', 358 },
  { ' ', 358 },
  { ':', -36 },
  { '=', -36 },
  { 'E', 371 },
  { '\t', 360 },
  { ' ', 360 },
  { ':', -37 },
  { '=', -37 },
  { '\t', 361 },
  { ' ', 361 },
  { ':', -34 },
  { '=', -34 },
  { 'U', 372 },
  { 'A', 373 },
  { '\t', 374 },
  { ' ', 374 },
  { ':', -38 },
  { '=', -38 },
  { 'D', 375 },
  { 'E', 376 },
  { '\t', 366 },
  { ' ', 366 },
  { ':', -39 },
  { '=', -39 },
  { '\t', 367 },
  { ' ', 367 },
  { ':', -40 },
  { '=', -40 },
  { '\t', 368 },
  { ' ', 368 },
  { '0', 377 },
  { '\t', 369 },
  { ' ', 369 },
  { ':', -41 },
  { '=', -41 },
  { 'E', 378 },
  { 'R', 379 },
  { 'A', 380 },
  { 'L', 381 },
  { '\t', 374 },
  { ' ', 374 },
  { ':', -38 },
  { '=', -38 },
  { 'U', 382 },
  { '\t', 376 },
  { '\n', -42 },
  { '\r', -42 },
  { ' ', 376 },
  { 'X', -43 },
  { '\t', 378 },
  { ' ', 378 },
  { ':', -44 },
  { '=', -44 },
  { '\t', 379 },
  { ' ', 379 },
  { ':', -45 },
  { '=', -45 },
  { 'L', 383 },
  { '\t', 381 },
  { ' ', 381 },
  { ':', -46 },
  { '=', -46 },
  { 'A', 384 },
  { '\t', 383 },
  { ' ', 383 },
  { ':', -47 },
  { '=', -47 },
  { 'L', 385 },
  { '\t', 385 },
  { ' ', 385 },
  { ':', -48 },
  { '=', -48 },
};

static const uint16 states[387] = {
  0,
  3,
  4,
  7,
  16,
  18,
  19,
  20,
  21,
  22,
  24,
  25,
  26,
  28,
  29,
  30,
  32,
  33,
  34,
  35,
  37,
  43,
  44,
  45,
  46,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  109,
  110,
  111,
  112,
  113,
  114,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  179,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  196,
  197,
  198,
  199,
  200,
  201,
  202,
  203,
  204,
  208,
  209,
  213,
  214,
  215,
  216,
  218,
  219,
  220,
  224,
  225,
  226,
  227,
  228,
  229,
  230,
  231,
  232,
  236,
  237,
  238,
  239,
  240,
  241,
  242,
  243,
  247,
  248,
  249,
  250,
  251,
  252,
  253,
  254,
  255,
  256,
  260,
  261,
  262,
  263,
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  275,
  279,
  280,
  281,
  282,
  283,
  284,
  286,
  287,
  288,
  289,
  290,
  291,
  292,
  294,
  298,
  299,
  300,
  301,
  302,
  304,
  305,
  306,
  307,
  308,
  312,
  313,
  314,
  315,
  316,
  317,
  318,
  319,
  323,
  324,
  325,
  329,
  330,
  331,
  332,
  336,
  337,
  338,
  339,
  344,
  349,
  350,
  351,
  355,
  356,
  357,
  358,
  359,
  360,
  361,
  362,
  363,
  364,
  365,
  370,
  371,
  372,
  373,
  374,
  375,
  378,
  379,
  380,
  383,
  384,
  385,
  386,
  391,
  392,
  393,
  398,
  403,
  404,
  408,
  409,
  410,
  411,
  412,
  413,
  414,
  415,
  416,
  417,
  418,
  423,
  424,
  425,
  427,
  428,
  429,
  430,
  431,
  432,
  433,
  434,
  435,
  439,
  444,
  448,
  449,
  453,
  457,
  461,
  465,
  466,
  467,
  468,
  469,
  471,
  475,
  476,
  477,
  481,
  485,
  486,
  487,
  488,
  492,
  496,
  500,
  501,
  506,
  507,
  508,
  512,
  516,
  517,
  518,
  519,
  523,
  524,
  525,
  526,
  527,
  528,
  532,
  533,
  538,
  542,
  543,
  544,
  545,
  546,
  547,
  551,
  552,
  553,
  557,
  561,
  562,
  566,
  570,
  571,
  572,
  577,
  578,
  582,
  586,
  589,
  593,
  594,
  595,
  596,
  597,
  601,
  602,
  606,
  607,
  611,
  615,
  616,
  620,
  621,
  625,
  626,
  630,
};

static uint16 matchLiteral(ptr s, ptr e, Task task)
{ s=s; e=e; task=task; return 0; }

ptr DeviceTestServiceParser_parseData(ptr s, ptr e, Task task)
{
  ptr p;

#ifdef DISPLAY_AT_CMDS
  {
    ptr c = s;
    printf("\nreceived: ");
    while (c != e)
    {
      uint8 ch = *c;
      if (ch == (uint8)13)         printf("\\r");
      else if (ch == (uint8)10)    printf("\\n\n");
      else                         printf("%c",ch);

      c++;
    }
    /* On the target a LF causes output to be printed */
    if (*(c-1) != (uint8)10)
    {
      printf("\n");
    }
  }
#endif

#ifdef TEST_HARNESS
  task = task;
#endif
  for(; (p = findEndOfPacket(s, e)) != 0; s = p)
  {
    if(p == s+1)
    {
      /* Silently discard one character; no packets are that short */
      continue;
    }
    else if(matchLiteral(s, p, task))
    {
      continue;
    }
    else
    {
      union {
        struct DeviceTestServiceCommand_HandleLed DeviceTestServiceCommand_HandleLed;
        struct DeviceTestServiceCommand_HandleAuthResp DeviceTestServiceCommand_HandleAuthResp;
        struct DeviceTestServiceCommand_HandlePskeyGet DeviceTestServiceCommand_HandlePskeyGet;
        struct DeviceTestServiceCommand_HandlePskeySet DeviceTestServiceCommand_HandlePskeySet;
        struct DeviceTestServiceCommand_HandleAncEnable DeviceTestServiceCommand_HandleAncEnable;
        struct DeviceTestServiceCommand_HandleTouchSensor DeviceTestServiceCommand_HandleTouchSensor;
        struct DeviceTestServiceCommand_HandlePskeyClear DeviceTestServiceCommand_HandlePskeyClear;
        struct DeviceTestServiceCommand_HandleMibPskeyGet DeviceTestServiceCommand_HandleMibPskeyGet;
        struct DeviceTestServiceCommand_HandleAncGetPsKey DeviceTestServiceCommand_HandleAncGetPsKey;
        struct DeviceTestServiceCommand_HandleAncSetPsKey DeviceTestServiceCommand_HandleAncSetPsKey;
        struct DeviceTestServiceCommand_HandleAudioPlayTone DeviceTestServiceCommand_HandleAudioPlayTone;
        struct DeviceTestServiceCommand_HandleDtsEndTesting DeviceTestServiceCommand_HandleDtsEndTesting;
        struct DeviceTestServiceCommand_HandleAudioLoopbackStart DeviceTestServiceCommand_HandleAudioLoopbackStart;
        struct DeviceTestServiceCommand_HandleRfTestCarrier DeviceTestServiceCommand_HandleRfTestCarrier;
        struct DeviceTestServiceCommand_HandlePioOutput DeviceTestServiceCommand_HandlePioOutput;
        struct DeviceTestServiceCommand_HandleProximitySensor DeviceTestServiceCommand_HandleProximitySensor;
        struct DeviceTestServiceCommand_HandleAncSetFineGain DeviceTestServiceCommand_HandleAncSetFineGain;
        struct DeviceTestServiceCommand_HandleDtsSetTestMode DeviceTestServiceCommand_HandleDtsSetTestMode;
        struct DeviceTestServiceCommand_HandleRfTestCfgPower DeviceTestServiceCommand_HandleRfTestCfgPower;
        struct DeviceTestServiceCommand_HandleHallEffectSensor DeviceTestServiceCommand_HandleHallEffectSensor;
        struct DeviceTestServiceCommand_HandleAncReadFineGain DeviceTestServiceCommand_HandleAncReadFineGain;
        struct DeviceTestServiceCommand_HandleRfTestLeRxStart DeviceTestServiceCommand_HandleRfTestLeRxStart;
        struct DeviceTestServiceCommand_HandleRfTestLeTxStart DeviceTestServiceCommand_HandleRfTestLeTxStart;
        struct DeviceTestServiceCommand_HandlePioInput DeviceTestServiceCommand_HandlePioInput;
        struct DeviceTestServiceCommand_HandleAncWriteFineGain DeviceTestServiceCommand_HandleAncWriteFineGain;
        struct DeviceTestServiceCommand_HandleRfTestCfgAddress DeviceTestServiceCommand_HandleRfTestCfgAddress;
        struct DeviceTestServiceCommand_HandleRfTestCfgChannel DeviceTestServiceCommand_HandleRfTestCfgChannel;
        struct DeviceTestServiceCommand_HandleRfTestCfgStopPio DeviceTestServiceCommand_HandleRfTestCfgStopPio;
        struct DeviceTestServiceCommand_HandleRfTestCfgPacket DeviceTestServiceCommand_HandleRfTestCfgPacket;
        struct DeviceTestServiceCommand_HandleRfTestCfgStopTime DeviceTestServiceCommand_HandleRfTestCfgStopTime;
        struct DeviceTestServiceCommand_HandleAccelerometer DeviceTestServiceCommand_HandleAccelerometer;
        struct DeviceTestServiceCommand_HandleAncSetFineGainDual DeviceTestServiceCommand_HandleAncSetFineGainDual;
        struct DeviceTestServiceCommand_HandleAncReadFineGainDual DeviceTestServiceCommand_HandleAncReadFineGainDual;
        struct DeviceTestServiceCommand_HandleAncWriteFineGainDual DeviceTestServiceCommand_HandleAncWriteFineGainDual;
      } u, *uu = &u;
      int state = 0;
      ptr t = s;
      while(t != e && state >= 0)
      {
        char m = my_toupper((char) *t);
        const Arc *a = &arcs[states[state]];
        const Arc *const last_a = &arcs[states[state+1]];
#ifndef TEST_HARNESS
        a = (const Arc *) (void *) UtilFind(0xFFFF, (uint16) m, (const uint16 *) (void *) &a[0].c, 0, sizeof(Arc), (uint16) (last_a - a));
#endif
#ifdef TEST_HARNESS
        while(a != last_a && a->c != m) a++;
#endif
        /*lint -e{801} suppress goto is deprecated */
        if(!a) goto unrecognised;
        state = a->to;
        ++t;
      }
      switch(-state)
      {
        case 1:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleLed.ledValue), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleLed(task, &uu->DeviceTestServiceCommand_HandleLed);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleLed");
            printf(" ledValue=%d", uu->DeviceTestServiceCommand_HandleLed.ledValue);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 2:
          if(match1(skip1(getClassPlus(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAuthResp.response, hexdigit), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAuthResp(task, &uu->DeviceTestServiceCommand_HandleAuthResp);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAuthResp");
            printString("response", &uu->DeviceTestServiceCommand_HandleAuthResp.response);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 3:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandlePskeyGet.pskey), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePskeyGet(task, &uu->DeviceTestServiceCommand_HandlePskeyGet);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePskeyGet");
            printf(" pskey=%d", uu->DeviceTestServiceCommand_HandlePskeyGet.pskey);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 4:
          if(match1(skip1(getWildString(skip1(skipOnce1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandlePskeySet.pskey), e), e), e, &uu->DeviceTestServiceCommand_HandlePskeySet.value), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePskeySet(task, &uu->DeviceTestServiceCommand_HandlePskeySet);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePskeySet");
            printf(" pskey=%d", uu->DeviceTestServiceCommand_HandlePskeySet.pskey);
            printString("value", &uu->DeviceTestServiceCommand_HandlePskeySet.value);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 5:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRssiRead(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRssiRead");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 6:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncEnable.mode), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncEnable(task, &uu->DeviceTestServiceCommand_HandleAncEnable);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncEnable");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncEnable.mode);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 7:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAuthStart(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAuthStart");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 8:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleTouchSensor.durationS), e), e), e), e, &uu->DeviceTestServiceCommand_HandleTouchSensor.stopAfter), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleTouchSensor(task, &uu->DeviceTestServiceCommand_HandleTouchSensor);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleTouchSensor");
            printf(" durationS=%d", uu->DeviceTestServiceCommand_HandleTouchSensor.durationS);
            printf(" stopAfter=%d", uu->DeviceTestServiceCommand_HandleTouchSensor.stopAfter);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 9:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncDisable(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncDisable");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 10:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandlePskeyClear.pskey), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePskeyClear(task, &uu->DeviceTestServiceCommand_HandlePskeyClear);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePskeyClear");
            printf(" pskey=%d", uu->DeviceTestServiceCommand_HandlePskeyClear.pskey);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 11:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestStop(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestStop");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 12:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAuthDisable(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAuthDisable");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 13:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDtsTestModeQuery(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDtsTestModeQuery");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 14:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleLocalBdaddr(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleLocalBdaddr");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 15:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleMibPskeyGet.pskey), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleMibPskeyGet(task, &uu->DeviceTestServiceCommand_HandleMibPskeyGet);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleMibPskeyGet");
            printf(" pskey=%d", uu->DeviceTestServiceCommand_HandleMibPskeyGet.pskey);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 16:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleTemperature(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleTemperature");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 17:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleBatteryLevel(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleBatteryLevel");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 18:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAudioLoopbackStop(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAudioLoopbackStop");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 19:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(getClassPlus(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncGetPsKey.pskey, hexdigit), e), e), e, &uu->DeviceTestServiceCommand_HandleAncGetPsKey.instance), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncGetPsKey(task, &uu->DeviceTestServiceCommand_HandleAncGetPsKey);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncGetPsKey");
            printString("pskey", &uu->DeviceTestServiceCommand_HandleAncGetPsKey.pskey);
            printf(" instance=%d", uu->DeviceTestServiceCommand_HandleAncGetPsKey.instance);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 20:
          if(match1(skip1(getWildString(skip1(skipOnce1(UtilGetNumber(skip1(skipOnce1(getClassPlus(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncSetPsKey.pskey, hexdigit), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetPsKey.instance), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetPsKey.value), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncSetPsKey(task, &uu->DeviceTestServiceCommand_HandleAncSetPsKey);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncSetPsKey");
            printString("pskey", &uu->DeviceTestServiceCommand_HandleAncSetPsKey.pskey);
            printf(" instance=%d", uu->DeviceTestServiceCommand_HandleAncSetPsKey.instance);
            printString("value", &uu->DeviceTestServiceCommand_HandleAncSetPsKey.value);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 21:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAudioPlayTone.tone), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAudioPlayTone.speakerSelection), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAudioPlayTone.durationMs), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAudioPlayTone(task, &uu->DeviceTestServiceCommand_HandleAudioPlayTone);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAudioPlayTone");
            printf(" tone=%d", uu->DeviceTestServiceCommand_HandleAudioPlayTone.tone);
            printf(" speakerSelection=%d", uu->DeviceTestServiceCommand_HandleAudioPlayTone.speakerSelection);
            printf(" durationMs=%d", uu->DeviceTestServiceCommand_HandleAudioPlayTone.durationMs);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 22:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleDtsEndTesting.reboot), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDtsEndTesting(task, &uu->DeviceTestServiceCommand_HandleDtsEndTesting);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDtsEndTesting");
            printf(" reboot=%d", uu->DeviceTestServiceCommand_HandleDtsEndTesting.reboot);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 23:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(UtilGetNumber(skip1(skipOnce1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.micSelection), e), e), e, &uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.speakerSelection), e), e), e, &uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.sampleRate), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAudioLoopbackStart(task, &uu->DeviceTestServiceCommand_HandleAudioLoopbackStart);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAudioLoopbackStart");
            printf(" micSelection=%d", uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.micSelection);
            printf(" speakerSelection=%d", uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.speakerSelection);
            printf(" sampleRate=%d", uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.sampleRate);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 24:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCarrier.channel), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCarrier(task, &uu->DeviceTestServiceCommand_HandleRfTestCarrier);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCarrier");
            printf(" channel=%d", uu->DeviceTestServiceCommand_HandleRfTestCarrier.channel);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 25:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDeviceUnderTestMode(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDeviceUnderTestMode");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 26:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestTxStart(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestTxStart");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 27:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePioAllInputs(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePioAllInputs");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 28:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandlePioOutput.pio), e), e), e, &uu->DeviceTestServiceCommand_HandlePioOutput.onOff), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePioOutput(task, &uu->DeviceTestServiceCommand_HandlePioOutput);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePioOutput");
            printf(" pio=%d", uu->DeviceTestServiceCommand_HandlePioOutput.pio);
            printf(" onOff=%d", uu->DeviceTestServiceCommand_HandlePioOutput.onOff);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 29:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleProximitySensor.durationS), e), e), e), e, &uu->DeviceTestServiceCommand_HandleProximitySensor.stopAfter), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleProximitySensor(task, &uu->DeviceTestServiceCommand_HandleProximitySensor);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleProximitySensor");
            printf(" durationS=%d", uu->DeviceTestServiceCommand_HandleProximitySensor.durationS);
            printf(" stopAfter=%d", uu->DeviceTestServiceCommand_HandleProximitySensor.stopAfter);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 30:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGain.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGain.gainpath), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGain.gainvalue), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncSetFineGain(task, &uu->DeviceTestServiceCommand_HandleAncSetFineGain);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncSetFineGain");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGain.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGain.gainpath);
            printf(" gainvalue=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGain.gainvalue);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 31:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleDtsSetTestMode.testmode), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDtsSetTestMode(task, &uu->DeviceTestServiceCommand_HandleDtsSetTestMode);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDtsSetTestMode");
            printf(" testmode=%d", uu->DeviceTestServiceCommand_HandleDtsSetTestMode.testmode);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 32:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgPower.powerSetting), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgPower(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgPower);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgPower");
            printf(" powerSetting=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgPower.powerSetting);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 33:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleHallEffectSensor.durationS), e), e), e), e, &uu->DeviceTestServiceCommand_HandleHallEffectSensor.stopAfter), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleHallEffectSensor(task, &uu->DeviceTestServiceCommand_HandleHallEffectSensor);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleHallEffectSensor");
            printf(" durationS=%d", uu->DeviceTestServiceCommand_HandleHallEffectSensor.durationS);
            printf(" stopAfter=%d", uu->DeviceTestServiceCommand_HandleHallEffectSensor.stopAfter);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 34:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncReadFineGain.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncReadFineGain.gainpath), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncReadFineGain(task, &uu->DeviceTestServiceCommand_HandleAncReadFineGain);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncReadFineGain");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncReadFineGain.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncReadFineGain.gainpath);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 35:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestLeRxStart.lechannel), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestLeRxStart(task, &uu->DeviceTestServiceCommand_HandleRfTestLeRxStart);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestLeRxStart");
            printf(" lechannel=%d", uu->DeviceTestServiceCommand_HandleRfTestLeRxStart.lechannel);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 36:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(UtilGetNumber(skip1(skipOnce1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.lechannel), e), e), e, &uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.lelength), e), e), e, &uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.pattern), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestLeTxStart(task, &uu->DeviceTestServiceCommand_HandleRfTestLeTxStart);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestLeTxStart");
            printf(" lechannel=%d", uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.lechannel);
            printf(" lelength=%d", uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.lelength);
            printf(" pattern=%d", uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.pattern);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 37:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandlePioInput.pio), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePioInput(task, &uu->DeviceTestServiceCommand_HandlePioInput);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePioInput");
            printf(" pio=%d", uu->DeviceTestServiceCommand_HandlePioInput.pio);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 38:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGain.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGain.gainpath), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGain.gainvalue), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncWriteFineGain(task, &uu->DeviceTestServiceCommand_HandleAncWriteFineGain);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncWriteFineGain");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGain.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGain.gainpath);
            printf(" gainvalue=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGain.gainvalue);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 39:
          if(match1(skip1(getClassPlus(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgAddress.logicalAddr), e), e), e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgAddress.bdaddr, hexdigit), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgAddress(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgAddress);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgAddress");
            printf(" logicalAddr=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgAddress.logicalAddr);
            printString("bdaddr", &uu->DeviceTestServiceCommand_HandleRfTestCfgAddress.bdaddr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 40:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgChannel.channel), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgChannel(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgChannel);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgChannel");
            printf(" channel=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgChannel.channel);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 41:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgStopPio.pio), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgStopPio(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgStopPio);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgStopPio");
            printf(" pio=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgStopPio.pio);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 42:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAudioPlayTestTone(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAudioPlayTestTone");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 43:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(getClassPlus(skip1(matchChar(matchChar(skip1(skipOnce1(skip1(getClassPlus(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.payload, hexdigit), e), e), e), e, '0'), e, 'X'), e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.packetType, hexdigit), e), e), e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.length), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgPacket(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgPacket");
            printString("payload", &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.payload);
            printString("packetType", &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.packetType);
            printf(" length=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.length);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 44:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgStopTime.reboot), e), e), e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgStopTime.timeMs), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgStopTime(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgStopTime);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgStopTime");
            printf(" reboot=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgStopTime.reboot);
            printf(" timeMs=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgStopTime.timeMs);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 45:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAccelerometer.durationS), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAccelerometer.stopAfter), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAccelerometer(task, &uu->DeviceTestServiceCommand_HandleAccelerometer);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAccelerometer");
            printf(" durationS=%d", uu->DeviceTestServiceCommand_HandleAccelerometer.durationS);
            printf(" stopAfter=%d", uu->DeviceTestServiceCommand_HandleAccelerometer.stopAfter);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 46:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.gainpath), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.instance0gain), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.instance1gain), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncSetFineGainDual(task, &uu->DeviceTestServiceCommand_HandleAncSetFineGainDual);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncSetFineGainDual");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.gainpath);
            printf(" instance0gain=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.instance0gain);
            printf(" instance1gain=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.instance1gain);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 47:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncReadFineGainDual.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncReadFineGainDual.gainpath), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncReadFineGainDual(task, &uu->DeviceTestServiceCommand_HandleAncReadFineGainDual);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncReadFineGainDual");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncReadFineGainDual.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncReadFineGainDual.gainpath);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 48:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.gainpath), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.instance0gain), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.instance1gain), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncWriteFineGainDual(task, &uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncWriteFineGainDual");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.gainpath);
            printf(" instance0gain=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.instance0gain);
            printf(" instance1gain=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.instance1gain);
            putchar('\n');
#endif
            continue;
          }
          break;
        default:
          break;
      }
      /*
        The message does not contain a recognised AT command or response.
        Pass the data on to the application to have a go at 
      */
unrecognised:
#ifndef TEST_HARNESS
      DeviceTestServiceParser_handleUnrecognised(s, (uint16) (p-s), task);
#endif
#ifdef TEST_HARNESS
      printf("Called handleUnrecognised\n");
#endif
    }
  }

  return s;
}

/*
DeviceTestServiceCommand_HandleAuthStart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar U
   MatchChar T
   MatchChar H
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAuthResp
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar U
   MatchChar T
   MatchChar H
   MatchChar R
   MatchChar E
   MatchChar S
   MatchChar P
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetClassPlus response
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAuthDisable
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar U
   MatchChar T
   MatchChar H
   MatchChar D
   MatchChar I
   MatchChar S
   MatchChar A
   MatchChar B
   MatchChar L
   MatchChar E
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDtsEndTesting
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar D
   MatchChar T
   MatchChar S
   MatchChar E
   MatchChar N
   MatchChar D
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar I
   MatchChar N
   MatchChar G
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber reboot
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDtsSetTestMode
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar D
   MatchChar T
   MatchChar S
   MatchChar S
   MatchChar E
   MatchChar T
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar M
   MatchChar O
   MatchChar D
   MatchChar E
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber testmode
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDtsTestModeQuery
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar D
   MatchChar T
   MatchChar S
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar M
   MatchChar O
   MatchChar D
   MatchChar E
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncEnable
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar E
   MatchChar N
   MatchChar A
   MatchChar B
   MatchChar L
   MatchChar E
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncDisable
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar D
   MatchChar I
   MatchChar S
   MatchChar A
   MatchChar B
   MatchChar L
   MatchChar E
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncReadFineGain
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar R
   MatchChar E
   MatchChar A
   MatchChar D
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncSetFineGain
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar S
   MatchChar E
   MatchChar T
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainvalue
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncWriteFineGain
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar W
   MatchChar R
   MatchChar I
   MatchChar T
   MatchChar E
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainvalue
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncReadFineGainDual
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar R
   MatchChar E
   MatchChar A
   MatchChar D
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   MatchChar D
   MatchChar U
   MatchChar A
   MatchChar L
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncSetFineGainDual
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar S
   MatchChar E
   MatchChar T
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   MatchChar D
   MatchChar U
   MatchChar A
   MatchChar L
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance0gain
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance1gain
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncWriteFineGainDual
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar W
   MatchChar R
   MatchChar I
   MatchChar T
   MatchChar E
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   MatchChar D
   MatchChar U
   MatchChar A
   MatchChar L
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance0gain
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance1gain
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncSetPsKey
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar S
   MatchChar E
   MatchChar T
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   Skip " \t"
   Match "=:"
   Skip " \t"
   MatchChar 0
   MatchChar X
   Skip " \t"
   GetClassPlus pskey
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance
   SkipOnce ",;"
   Skip " \t"
   GetWildString value
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncGetPsKey
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar G
   MatchChar E
   MatchChar T
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   Skip " \t"
   Match "=:"
   Skip " \t"
   MatchChar 0
   MatchChar X
   Skip " \t"
   GetClassPlus pskey
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleLocalBdaddr
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar L
   MatchChar O
   MatchChar C
   MatchChar A
   MatchChar L
   MatchChar B
   MatchChar D
   MatchChar A
   MatchChar D
   MatchChar D
   MatchChar R
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAudioLoopbackStart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar L
   MatchChar O
   MatchChar O
   MatchChar P
   MatchChar B
   MatchChar A
   MatchChar C
   MatchChar K
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber micSelection
   SkipOnce ",;"
   Skip " \t"
   GetNumber speakerSelection
   SkipOnce ",;"
   Skip " \t"
   GetNumber sampleRate
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAudioLoopbackStop
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar L
   MatchChar O
   MatchChar O
   MatchChar P
   MatchChar B
   MatchChar A
   MatchChar C
   MatchChar K
   MatchChar S
   MatchChar T
   MatchChar O
   MatchChar P
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAudioPlayTestTone
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar U
   MatchChar D
   MatchChar I
   MatchChar O
   MatchChar P
   MatchChar L
   MatchChar A
   MatchChar Y
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar T
   MatchChar O
   MatchChar N
   MatchChar E
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAudioPlayTone
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar U
   MatchChar D
   MatchChar I
   MatchChar O
   MatchChar P
   MatchChar L
   MatchChar A
   MatchChar Y
   MatchChar T
   MatchChar O
   MatchChar N
   MatchChar E
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber tone
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber speakerSelection
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber durationMs
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestStop
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar S
   MatchChar T
   MatchChar O
   MatchChar P
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCarrier
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar A
   MatchChar R
   MatchChar R
   MatchChar I
   MatchChar E
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber channel
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestTxStart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar T
   MatchChar X
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgChannel
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar C
   MatchChar H
   MatchChar A
   MatchChar N
   MatchChar N
   MatchChar E
   MatchChar L
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber channel
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgPacket
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar P
   MatchChar A
   MatchChar C
   MatchChar K
   MatchChar E
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   MatchChar 0
   MatchChar X
   Skip " \t"
   GetClassPlus payload
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   MatchChar 0
   MatchChar X
   Skip " \t"
   GetClassPlus packetType
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber length
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgAddress
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar A
   MatchChar D
   MatchChar D
   MatchChar R
   MatchChar E
   MatchChar S
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber logicalAddr
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetClassPlus bdaddr
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgPower
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar P
   MatchChar O
   MatchChar W
   MatchChar E
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber powerSetting
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgStopTime
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar O
   MatchChar P
   MatchChar T
   MatchChar I
   MatchChar M
   MatchChar E
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber reboot
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber timeMs
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgStopPio
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar O
   MatchChar P
   MatchChar P
   MatchChar I
   MatchChar O
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pio
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDeviceUnderTestMode
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar D
   MatchChar U
   MatchChar T
   MatchChar M
   MatchChar O
   MatchChar D
   MatchChar E
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestLeTxStart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar L
   MatchChar E
   MatchChar T
   MatchChar X
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber lechannel
   SkipOnce ",;"
   Skip " \t"
   GetNumber lelength
   SkipOnce ",;"
   Skip " \t"
   GetNumber pattern
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestLeRxStart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar L
   MatchChar E
   MatchChar R
   MatchChar X
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber lechannel
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePioOutput
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar P
   MatchChar I
   MatchChar O
   MatchChar O
   MatchChar U
   MatchChar T
   MatchChar P
   MatchChar U
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pio
   SkipOnce ",;"
   Skip " \t"
   GetNumber onOff
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePioInput
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar P
   MatchChar I
   MatchChar O
   MatchChar I
   MatchChar N
   MatchChar P
   MatchChar U
   MatchChar T
   MatchChar P
   MatchChar I
   MatchChar O
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pio
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePioAllInputs
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar P
   MatchChar I
   MatchChar O
   MatchChar I
   MatchChar N
   MatchChar P
   MatchChar U
   MatchChar T
   MatchChar S
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleLed
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar L
   MatchChar E
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber ledValue
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRssiRead
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar S
   MatchChar S
   MatchChar I
   MatchChar R
   MatchChar E
   MatchChar A
   MatchChar D
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePskeySet
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   MatchChar S
   MatchChar E
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pskey
   SkipOnce ",;"
   Skip " \t"
   GetWildString value
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePskeyGet
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   MatchChar G
   MatchChar E
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pskey
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePskeyClear
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   MatchChar C
   MatchChar L
   MatchChar E
   MatchChar A
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pskey
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleMibPskeyGet
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   MatchChar M
   MatchChar I
   MatchChar B
   MatchChar G
   MatchChar E
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pskey
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAccelerometer
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar C
   MatchChar C
   MatchChar E
   MatchChar L
   MatchChar E
   MatchChar R
   MatchChar O
   MatchChar M
   MatchChar E
   MatchChar T
   MatchChar E
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber durationS
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber stopAfter
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleProximitySensor
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar P
   MatchChar R
   MatchChar O
   MatchChar X
   MatchChar I
   MatchChar M
   MatchChar I
   MatchChar T
   MatchChar Y
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber durationS
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber stopAfter
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleTouchSensor
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar T
   MatchChar O
   MatchChar U
   MatchChar C
   MatchChar H
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber durationS
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber stopAfter
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleHallEffectSensor
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar H
   MatchChar A
   MatchChar L
   MatchChar L
   MatchChar E
   MatchChar F
   MatchChar F
   MatchChar E
   MatchChar C
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber durationS
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber stopAfter
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleTemperature
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar M
   MatchChar P
   MatchChar E
   MatchChar R
   MatchChar A
   MatchChar T
   MatchChar U
   MatchChar R
   MatchChar E
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleBatteryLevel
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar A
   MatchChar T
   MatchChar T
   MatchChar E
   MatchChar R
   MatchChar Y
   MatchChar L
   MatchChar E
   MatchChar V
   MatchChar E
   MatchChar L
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


*/
