/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The bt_device marshal type declarations. This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools/packages/typegen/typegen.py.
*/

#ifndef _BT_DEVICE_MARSHAL_TYPEDEF_H__
#define _BT_DEVICE_MARSHAL_TYPEDEF_H__

#include <csrtypes.h>
#include <csrtypes.h>
#include <marshal_common.h>
#include <app/marshal/marshal_if.h>

extern const marshal_type_descriptor_t marshal_type_descriptor_bt_device_pdd_t;

#define BT_DEVICE_MARSHAL_TYPES_TABLE(ENTRY)\
    ENTRY(bt_device_pdd_t)

#endif /* _BT_DEVICE_MARSHAL_TYPEDEF_H__ */

