/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The voice_ui_peer_sig marshal type definitions. This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools/packages/typegen/typegen.py.
*/

#include <csrtypes.h>
#include <app/marshal/marshal_if.h>
#include <voice_ui_peer_sig_typedef.h>
#include <voice_ui_peer_sig_marshal_typedef.h>

const marshal_type_descriptor_t marshal_type_descriptor_voice_ui_selected_va_provider_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(voice_ui_selected_va_provider_t);


#define EXPAND_AS_TYPE_DEFINITION(type) (const marshal_type_descriptor_t *)&marshal_type_descriptor_##type,
const marshal_type_descriptor_t * const voice_ui_peer_sig_marshal_type_descriptors[] =
{
    VOICE_UI_PEER_SIG_MARSHAL_TYPES_TABLE(EXPAND_AS_TYPE_DEFINITION)
} ;

#undef EXPAND_AS_TYPE_DEFINITION

