@startuml

    object OPR_LATENCY_BUFFER
    OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
    object EPR_WIRED_STEREO_INPUT_L #lightgreen
    OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
    object EPR_WIRED_STEREO_INPUT_R #lightgreen
    OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
    object EPR_SOURCE_DECODED_PCM #lightblue
    EPR_SOURCE_DECODED_PCM <-- "OUT_L(0)" OPR_LATENCY_BUFFER
    object EPR_SOURCE_DECODED_PCM_RIGHT #lightblue
    EPR_SOURCE_DECODED_PCM_RIGHT <-- "OUT_R(1)" OPR_LATENCY_BUFFER
@enduml
