@startuml

    object OPR_USB_AUDIO_RX
    OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
    object OPR_SPEAKER_RESAMPLER
    OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
    OPR_SPEAKER_RESAMPLER "IN(0)"<-- "OUT(0)" OPR_USB_AUDIO_RX
    object EPR_USB_FROM_HOST #lightgreen
    OPR_USB_AUDIO_RX "USB_IN(0)" <-- EPR_USB_FROM_HOST
    object EPR_USB_RX_RESAMPLER_OUT #lightblue
    EPR_USB_RX_RESAMPLER_OUT <-- "OUT(0)" OPR_SPEAKER_RESAMPLER
@enduml
