@startuml

    object OPR_RTP_DECODER
    OPR_RTP_DECODER : id = CAP_ID_RTP_DECODE
    object OPR_APTX_DECODER
    OPR_APTX_DECODER : id = CAP_ID_APTX_CLASSIC_DECODER
    OPR_APTX_DECODER "IN(0)"<-- "OUT(0)" OPR_RTP_DECODER
    object EPR_SINK_MEDIA #lightgreen
    OPR_RTP_DECODER "IN(0)" <-- EPR_SINK_MEDIA
    object EPR_SOURCE_DECODED_PCM #lightblue
    EPR_SOURCE_DECODED_PCM <-- "OUT_0(0)" OPR_APTX_DECODER
    object EPR_SOURCE_DECODED_PCM_RIGHT #lightblue
    EPR_SOURCE_DECODED_PCM_RIGHT <-- "OUT_1(1)" OPR_APTX_DECODER
@enduml
