/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The mirror_profile marshal type definitions. This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools/packages/typegen/typegen.py.
*/

#include <csrtypes.h>
#include <kymera_adaptation_voice_protected.h>
#include <app/marshal/marshal_if.h>
#include <mirror_profile_typedef.h>
#include <mirror_profile_marshal_typedef.h>
#include <marshal_common.h>

/*! A2DP media stream context sent from Primary to Secondary */
static const marshal_member_descriptor_t mirror_profile_stream_context_t_member_descriptors[] =
{
    /*! The BT address */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, bdaddr, addr),
    /*! L2CAP CID */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint16, cid),
    /*! L2CAP maximum transmission unit */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint16, mtu),
    /*! A2DP volume */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint8, volume),
    /*! Defines the current audio state - disconnected, connected, active */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint8, audio_state),
    /*! Negotiated AVDTP SEID (stream endpoing ID)  */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint8, seid),
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint8, codec_sub_type),
    /*! Codec bitrate bps */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint32, bitrate),
    /*! Audio sample rate (/25Hz) */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint16, sample_rate),
    /*! Audio sample bit width */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint8, sample_width),
    /*! Audio channel type */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint8, channel_type),
    /*! Audio source */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint8, audio_source),
    /*! Other flags */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint8, flags),
    /*! Content protection type */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint16, content_protection_type),
    /*! Length of extra CPI (always 0) */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint8, content_protection_information_length),
    /*! Q2Q Mode */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint8, q2q_mode),
    /*! Split Mode */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_t, uint32, aptx_features),
} ;

/*! A2DP media stream context response sent from Secondary to Primary */
static const marshal_member_descriptor_t mirror_profile_stream_context_response_t_member_descriptors[] =
{
    /*! L2CAP CID */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_response_t, uint16, cid),
    /*! Negotiated AVDTP SEID (stream endpoing ID)  */
    MAKE_MARSHAL_MEMBER(mirror_profile_stream_context_response_t, uint8, seid),
} ;

/*! Secondary sends this message to primary to tell it when to unmute during a mute-sync start */
static const marshal_member_descriptor_t mirror_profile_sync_unmute_ind_t_member_descriptors[] =
{
    /*! The time at which to unmute */
    MAKE_MARSHAL_MEMBER(mirror_profile_sync_unmute_ind_t, marshal_rtime_t, unmute_time),
} ;

const marshal_type_descriptor_t marshal_type_descriptor_mirror_profile_hfp_volume_ind_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(mirror_profile_hfp_volume_ind_t);
const marshal_type_descriptor_t marshal_type_descriptor_mirror_profile_hfp_codec_and_volume_ind_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(mirror_profile_hfp_codec_and_volume_ind_t);
const marshal_type_descriptor_t marshal_type_descriptor_mirror_profile_a2dp_volume_ind_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(mirror_profile_a2dp_volume_ind_t);
const marshal_type_descriptor_t marshal_type_descriptor_mirror_profile_stream_context_t = MAKE_MARSHAL_TYPE_DEFINITION(mirror_profile_stream_context_t, mirror_profile_stream_context_t_member_descriptors);
const marshal_type_descriptor_t marshal_type_descriptor_mirror_profile_stream_context_response_t = MAKE_MARSHAL_TYPE_DEFINITION(mirror_profile_stream_context_response_t, mirror_profile_stream_context_response_t_member_descriptors);
const marshal_type_descriptor_t marshal_type_descriptor_mirror_profile_sync_unmute_ind_t = MAKE_MARSHAL_TYPE_DEFINITION(mirror_profile_sync_unmute_ind_t, mirror_profile_sync_unmute_ind_t_member_descriptors);


#define EXPAND_AS_TYPE_DEFINITION(type) (const marshal_type_descriptor_t *)&marshal_type_descriptor_##type,
const marshal_type_descriptor_t * const mirror_profile_marshal_type_descriptors[] =
{
    MARSHAL_COMMON_TYPES_TABLE(EXPAND_AS_TYPE_DEFINITION)
    MIRROR_PROFILE_MARSHAL_TYPES_TABLE(EXPAND_AS_TYPE_DEFINITION)
} ;

#undef EXPAND_AS_TYPE_DEFINITION

