/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The mirror_profile c type definitions. This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools/packages/typegen/typegen.py.
*/

#ifndef _MIRROR_PROFILE_TYPEDEF_H__
#define _MIRROR_PROFILE_TYPEDEF_H__

#include <csrtypes.h>
#include <kymera_adaptation_voice_protected.h>
#include <marshal_common.h>

/*! HFP volume update sent from Primary to Secondary */
typedef struct 
{
    /*! Voice source */
    uint8 voice_source;
    /*! HFP volume */
    uint8 volume;
} mirror_profile_hfp_volume_ind_t;

/*! HFP codec type and volume sent from Primary to Secondary */
typedef struct 
{
    /*! Voice source */
    uint8 voice_source;
    /*! HFP codec */
    hfp_codec_mode_t codec_mode;
    /*! HFP volume */
    uint8 volume;
} mirror_profile_hfp_codec_and_volume_ind_t;

/*! A2DP volume update sent from Primary to Secondary */
typedef struct 
{
    /*! Audio source */
    uint8 audio_source;
    /*! A2DP volume */
    uint8 volume;
} mirror_profile_a2dp_volume_ind_t;

/*! A2DP media stream context sent from Primary to Secondary */
typedef struct 
{
    /*! The BT address */
    bdaddr addr;
    /*! L2CAP CID */
    uint16 cid;
    /*! L2CAP maximum transmission unit */
    uint16 mtu;
    /*! A2DP volume */
    uint8 volume;
    /*! Defines the current audio state - disconnected, connected, active */
    uint8 audio_state;
    /*! Negotiated AVDTP SEID (stream endpoing ID)  */
    uint8 seid;
    uint8 codec_sub_type;
    /*! Codec bitrate bps */
    uint32 bitrate;
    /*! Audio sample rate (/25Hz) */
    uint16 sample_rate;
    /*! Audio sample bit width */
    uint8 sample_width;
    /*! Audio channel type */
    uint8 channel_type;
    /*! Audio source */
    uint8 audio_source;
    /*! Other flags */
    uint8 flags;
    /*! Content protection type */
    uint16 content_protection_type;
    /*! Length of extra CPI (always 0) */
    uint8 content_protection_information_length;
    /*! Q2Q Mode */
    uint8 q2q_mode;
    /*! Split Mode */
    uint32 aptx_features;
} mirror_profile_stream_context_t;

/*! A2DP media stream context response sent from Secondary to Primary */
typedef struct 
{
    /*! L2CAP CID */
    uint16 cid;
    /*! Negotiated AVDTP SEID (stream endpoing ID)  */
    uint8 seid;
} mirror_profile_stream_context_response_t;

/*! Secondary sends this message to primary to tell it when to unmute during a mute-sync start */
typedef struct 
{
    /*! The time at which to unmute */
    marshal_rtime_t unmute_time;
} mirror_profile_sync_unmute_ind_t;

#endif /* _MIRROR_PROFILE_TYPEDEF_H__ */

