/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The scofwd_profile c type definitions. This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools/packages/typegen/typegen.py.
*/

#ifndef _SCOFWD_PROFILE_TYPEDEF_H__
#define _SCOFWD_PROFILE_TYPEDEF_H__

#include <csrtypes.h>

/*! ScoFwd OTA message with no payload */
typedef struct 
{
    /*! ScoFwd OTA message Id */
    uint8 ota_msg_id;
} scofwd_profile_ota_message_ind_t;

/*! ScoFwd volume forwarded from peer */
typedef struct 
{
    /*! ScoFwd volume */
    uint8 volume;
} scofwd_profile_volume_ind_t;

/*! Start a repeating volume change */
typedef struct 
{
    /*! ScoFwd volume step change */
    int16 steps;
} scofwd_profile_volume_start_ind_t;

/*! Stop a repeating volume change */
typedef struct 
{
    /*! ScoFwd volume step change */
    int16 steps;
} scofwd_profile_volume_stop_ind_t;

#endif /* _SCOFWD_PROFILE_TYPEDEF_H__ */

