/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The scofwd_profile marshal type definitions. This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools/packages/typegen/typegen.py.
*/

#include <csrtypes.h>
#include <app/marshal/marshal_if.h>
#include <scofwd_profile_typedef.h>
#include <scofwd_profile_marshal_typedef.h>

const marshal_type_descriptor_t marshal_type_descriptor_scofwd_profile_ota_message_ind_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(scofwd_profile_ota_message_ind_t);
const marshal_type_descriptor_t marshal_type_descriptor_scofwd_profile_volume_ind_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(scofwd_profile_volume_ind_t);
const marshal_type_descriptor_t marshal_type_descriptor_scofwd_profile_volume_start_ind_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(scofwd_profile_volume_start_ind_t);
const marshal_type_descriptor_t marshal_type_descriptor_scofwd_profile_volume_stop_ind_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(scofwd_profile_volume_stop_ind_t);


#define EXPAND_AS_TYPE_DEFINITION(type) (const marshal_type_descriptor_t *)&marshal_type_descriptor_##type,
const marshal_type_descriptor_t * const scofwd_profile_marshal_type_descriptors[] =
{
    SCOFWD_PROFILE_MARSHAL_TYPES_TABLE(EXPAND_AS_TYPE_DEFINITION)
} ;

#undef EXPAND_AS_TYPE_DEFINITION

