/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The scofwd_profile marshal type declarations. This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src-1-0_qtil_standard_oem_headset-CS-r00261.1-b6022d9b12dafd39568892b0ca2f2d52672d950f\adk\tools/packages/typegen/typegen.py.
*/

#ifndef _SCOFWD_PROFILE_MARSHAL_TYPEDEF_H__
#define _SCOFWD_PROFILE_MARSHAL_TYPEDEF_H__

#include <csrtypes.h>
#include <app/marshal/marshal_if.h>


#define SCOFWD_PROFILE_MARSHAL_TYPES_TABLE(ENTRY)\
    ENTRY(scofwd_profile_ota_message_ind_t)\
    ENTRY(scofwd_profile_volume_ind_t)\
    ENTRY(scofwd_profile_volume_start_ind_t)\
    ENTRY(scofwd_profile_volume_stop_ind_t)

#define EXPAND_AS_ENUMERATION(type) MARSHAL_TYPE(type),
enum SCOFWD_PROFILE_MARSHAL_TYPES
{
    SCOFWD_PROFILE_MARSHAL_TYPES_TABLE(EXPAND_AS_ENUMERATION)
    NUMBER_OF_SCOFWD_PROFILE_MARSHAL_TYPES
} ;

#undef EXPAND_AS_ENUMERATION

extern const marshal_type_descriptor_t * const scofwd_profile_marshal_type_descriptors[];
#endif /* _SCOFWD_PROFILE_MARSHAL_TYPEDEF_H__ */

